version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install -y unzip
      - curl -O https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip -d /usr/local/bin/

  pre_build:
    commands:
      - cd terraform-aws-vpc-bastion
      - ls -R
      - terraform init

  build:
    commands:
      - cd terraform-aws-vpc-bastion
      - terraform plan -out=tfplan
