version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install -y unzip wget
      - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - echo "Running terraform init"
      - ls -R
      - terraform init

  build:
    commands:
      - echo "Running terraform plan and apply"
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan
